rasterizer:
  command: /usr/bin/slime   # phantomjs executable
  port: 5440           # internal service port. No need to allow inbound or outbound access to this port
  path: '/tmp/screencaps/'        # where the screenshot files are stored
  viewport: '1280x800' # browser window size. Height frows according to the content
cache:
  lifetime: 259200000      # one month (30 days), set to 0 for no cache
server:
  port: 3030           # main service port
  useCors: false       # enable CORS support
